### ISSUE TITLE
Issue running unit tests: cannot find contract attachment

### ISSUE THREAD

**Issue by jeromesimeon** [rogersanick/corda-accord-template#1]
I am having trouble running the Java unit test for the cordapp/template. The error seems to be related to how the attachment is created and/or accessed. Here is a slice of the log:

```
[INFO ] 12:42:34,670 [Test worker] (AbstractNode.kt:555) internal.InternalMockNetwork$MockNode.registerInitiatedFlowInternal - Registered net.corda.accord.flow.PromissoryNoteIssueFlow$InitiatorFlow to initiate net.corda.accord.flow.PromissoryNoteIssueFlow$ResponderFlow (version 1) {}
[INFO ] 12:42:34,671 [Test worker] (AbstractNode.kt:555) internal.InternalMockNetwork$MockNode.registerInitiatedFlowInternal - Registered net.corda.accord.flow.PromissoryNoteIssueFlow$InitiatorFlow to initiate net.corda.accord.flow.PromissoryNoteIssueFlow$ResponderFlow (version 1) {}
[INFO ] 12:42:34,727 [Test worker] (NodeAttachmentService.kt:297) persistence.NodeAttachmentService.invoke - Stored new attachment EF3E1D06F450D1A89894095F6992DA3C283166BBB57C4860A6724E60460DAE8A {}
[WARN ] 12:42:38,329 [Mock network] (FlowStateMachineImpl.kt:107) flow.[e4dc60ca-55a8-4353-aea6-dec47e148b04].run - Flow finished with exception {}
net.corda.core.transactions.MissingContractAttachments: Cannot find contract attachments for [PromissoryNoteContract]. See https://docs.corda.net/api-contract-constraints.html#debugging
	at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core(TransactionBuilder.kt:109) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core$default(TransactionBuilder.kt:97) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.transactions.TransactionBuilder.toWireTransaction(TransactionBuilder.kt:95) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.transactions.TransactionBuilder.toLedgerTransaction(TransactionBuilder.kt:135) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.transactions.TransactionBuilder.verify(TransactionBuilder.kt:143) ~[corda-core-3.2-corda.jar:?]
	at net.corda.accord.flow.PromissoryNoteIssueFlow$InitiatorFlow.call(PromissoryNoteIssueFlow.java:102) ~[main/:?]
	at net.corda.accord.flow.PromissoryNoteIssueFlow$InitiatorFlow.call(PromissoryNoteIssueFlow.java:32) ~[main/:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.2-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.2-corda.jar:?]
[INFO ] 12:42:38,375 [Test worker] (HikariPool.java:204) pool.HikariPool.shutdown - HikariPool-1 - Close initiated... {}
[INFO ] 12:42:38,379 [Test worker] (HikariPool.java:241) pool.HikariPool.shutdown - HikariPool-1 - Closed. {}
[INFO ] 12:42:38,380 [Test worker] (HikariPool.java:204) pool.HikariPool.shutdown - HikariPool-2 - Close initiated... {}
[INFO ] 12:42:38,382 [Test worker] (HikariPool.java:241) pool.HikariPool.shutdown - HikariPool-2 - Closed. {}
[INFO ] 12:42:38,383 [Test worker] (HikariPool.java:204) pool.HikariPool.shutdown - HikariPool-3 - Close initiated... {}
[INFO ] 12:42:38,384 [Test worker] (HikariPool.java:241) pool.HikariPool.shutdown - HikariPool-3 - Closed. {}
net.corda.accord.flow.PromissoryNoteIssueFlowTests > flowReturnsCorrectlyFormedPartiallySignedTransaction FAILED
    java.util.concurrent.ExecutionException at PromissoryNoteIssueFlowTests.java:133
        Caused by: net.corda.core.transactions.MissingContractAttachments
```

**Comment by rogersanick** [comment]
Fixed! This error message was frustratingly accurate. I had specified the wrong name for the package containing the contract and this error was being thrown when I attempted to reference it in a transaction.
